version: '3'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]

  redis:
    image: redis:5-alpine
    ports: [6379]

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]

  mailcatcher:
    image: schickling/mailcatcher
    ports: ["55052:1025", 1080]

  pgadmin:
    image: dpage/pgadmin4
    ports: [80]
    environment:
      PGADMIN_DEFAULT_EMAIL: joel.coll@gmail.com
      PGADMIN_DEFAULT_PASSWORD: main